function C_matrix = coriolis_lagrange(phi, theta, psi, phi_dot, theta_dot, psi_dot, Ixx, Iyy, Izz)
% =========================================================================
% FUNZIONE: coriolis_lagrange.m
% DESCRIZIONE: Calcola la matrice delle forze di Coriolis e centrifughe 
%              basata sul modello di Eulero-Lagrange (Tesi Raffo).
% =========================================================================

    % Pre-calcolo di seni e coseni (per ottimizzare i calcoli)
    s_phi = sin(phi);     c_phi = cos(phi);
    s_theta = sin(theta); c_theta = cos(theta);
    % (psi non compare nelle equazioni c_ij, ma lo passiamo per completezza)

    % Inizializzo la matrice 3x3
    C_matrix = zeros(3,3);

    % --- ELEMENTI DELLA MATRICE DI CORIOLIS ---

    % Riga 1
    C_matrix(1,1) = 0;
    
    C_matrix(1,2) = (Iyy - Izz) * (theta_dot * c_phi * s_phi + 0.5 * psi_dot * (s_phi^2) * c_theta) ...
                  + 0.5 * (Izz - Iyy) * psi_dot * (c_phi^2) * c_theta ...
                  - 0.5 * Ixx * psi_dot * c_theta;
              
    C_matrix(1,3) = (Izz - Iyy) * (psi_dot * c_phi * s_phi * (c_theta^2) + 0.5 * theta_dot * c_theta * (c_phi^2)) ...
                  + 0.5 * (Iyy - Izz) * theta_dot * c_theta * (s_phi^2) ...
                  - 0.5 * Ixx * theta_dot * c_theta;

    % Riga 2
    C_matrix(2,1) = (Izz - Iyy) * (theta_dot * c_phi * s_phi + 0.5 * psi_dot * (s_phi^2) * c_theta) ...
                  + 0.5 * (Iyy - Izz) * psi_dot * (c_phi^2) * c_theta ...
                  + 0.5 * Ixx * psi_dot * c_theta;
              
    C_matrix(2,2) = (Izz - Iyy) * phi_dot * c_phi * s_phi;
    
    C_matrix(2,3) = -Ixx * psi_dot * s_theta * c_theta ...
                  + Iyy * psi_dot * (s_phi^2) * c_theta * s_theta ...
                  + Izz * psi_dot * (c_phi^2) * s_theta * c_theta ...
                  + 0.5 * (Iyy - Izz) * phi_dot * c_theta * (c_phi^2) ...
                  + 0.5 * (Izz - Iyy) * phi_dot * c_theta * (s_phi^2) ...
                  + 0.5 * Ixx * phi_dot * c_theta;

    % Riga 3
    C_matrix(3,1) = (Iyy - Izz) * (psi_dot * (c_theta^2) * s_phi * c_phi + 0.5 * theta_dot * c_theta * (c_phi^2)) ...
                  + 0.5 * (Izz - Iyy) * theta_dot * c_theta * (s_phi^2) ...
                  - 0.5 * Ixx * theta_dot * c_theta;
              
    C_matrix(3,2) = (Izz - Iyy) * (theta_dot * c_phi * s_phi * s_theta + 0.5 * phi_dot * (s_phi^2) * c_theta) ...
                  + 0.5 * (Iyy - Izz) * phi_dot * (c_phi^2) * c_theta ...
                  - 0.5 * Ixx * phi_dot * c_theta ...
                  + Ixx * psi_dot * s_theta * c_theta ...
                  - Iyy * psi_dot * (s_phi^2) * s_theta * c_theta ...
                  - Izz * psi_dot * (c_phi^2) * s_theta * c_theta;
              
    C_matrix(3,3) = (Iyy - Izz) * phi_dot * c_phi * s_phi * (c_theta^2) ...
                  - Iyy * theta_dot * (s_phi^2) * c_theta * s_theta ...
                  - Izz * theta_dot * (c_phi^2) * c_theta * s_theta ...
                  + Ixx * theta_dot * c_theta * s_theta;

end