/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int mpc_solver(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mpc_solver_alloc_mem(void);
int mpc_solver_init_mem(int mem);
void mpc_solver_free_mem(int mem);
int mpc_solver_checkout(void);
void mpc_solver_release(int mem);
void mpc_solver_incref(void);
void mpc_solver_decref(void);
casadi_int mpc_solver_n_in(void);
casadi_int mpc_solver_n_out(void);
casadi_real mpc_solver_default_in(casadi_int i);
const char* mpc_solver_name_in(casadi_int i);
const char* mpc_solver_name_out(casadi_int i);
const casadi_int* mpc_solver_sparsity_in(casadi_int i);
const casadi_int* mpc_solver_sparsity_out(casadi_int i);
int mpc_solver_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int mpc_solver_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mpc_solver_SZ_ARG 68
#define mpc_solver_SZ_RES 11
#define mpc_solver_SZ_IW 10320
#define mpc_solver_SZ_W 209822
#ifdef __cplusplus
} /* extern "C" */
#endif
